#!/bin/bash
# =============================================================
# Celtech Kiosk Update Script
# Hard-resets local working copy to match origin/main and
# regenerates config.js from /etc/celtech/env
# =============================================================

set -e

APP_DIR="/home/druid-mobile/celtech"
LOG_FILE="/home/druid-mobile/update.log"
ENV_FILE="/etc/celtech/env"
CONFIG_JS="$APP_DIR/app/js/config.js"
BRANCH="main"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "-----------------------------------"
log "Starting Celtech Driver App software update"

if [ ! -d "$APP_DIR/.git" ]; then
    log "ERROR: $APP_DIR is not a git repository. Aborting."
    exit 1
fi

cd "$APP_DIR"

# Wait for network (up to 30 seconds)
log "Waiting for network..."
WAIT=0
NETWORK_OK=1
until ping -c 1 -W 2 8.8.8.8 &>/dev/null; do
    WAIT=$((WAIT + 2))
    if [ $WAIT -ge 30 ]; then
        log "WARNING: No network after 30s. Skipping git update, continuing with existing version."
        NETWORK_OK=0
        break
    fi
    sleep 2
done

if [ $NETWORK_OK -eq 1 ]; then
    log "Network ready after ${WAIT}s."
    log "Fetching from origin..."
    git fetch origin "$BRANCH" >> "$LOG_FILE" 2>&1

    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse "origin/$BRANCH")

    if [ "$LOCAL" = "$REMOTE" ]; then
        if [ -n "$(git status --porcelain)" ]; then
            log "Local modifications detected, resetting to clean state..."
            git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
        fi
        log "Already up to date ($(git rev-parse --short HEAD)). No update needed."
    else
        log "Update available: $(git rev-parse --short HEAD) -> $(git rev-parse --short origin/$BRANCH)"
        git reset --hard "origin/$BRANCH" >> "$LOG_FILE" 2>&1
        log "Updated to: $(git rev-parse --short HEAD)"
    fi
fi

# Generate config.js from environment file (always run, even offline)
log "Generating config.js from $ENV_FILE..."
if [ ! -f "$ENV_FILE" ]; then
    log "WARNING: $ENV_FILE not found. config.js will have empty values."
    GOOGLE_MAPS_API_KEY=""
    MAPTILER_API_KEY=""
    ORS_API_KEY=""
else
    set -a
    source "$ENV_FILE"
    set +a
fi

cat > "$CONFIG_JS" <<EOF
// Auto-generated by update.sh — do not edit manually.
// Values come from $ENV_FILE
window.CELTECH_CONFIG = {
  GOOGLE_MAPS_API_KEY: '${GOOGLE_MAPS_API_KEY:-}',
  MAPTILER_API_KEY: '${MAPTILER_API_KEY:-}',
  ORS_API_KEY: '${ORS_API_KEY:-}'
};
EOF

# Report which keys are populated
if [ -n "${MAPTILER_API_KEY:-}" ]; then
    log "MAPTILER_API_KEY present (${#MAPTILER_API_KEY} chars)."
else
    log "WARNING: MAPTILER_API_KEY is empty — map features will not work."
fi

if [ -n "${ORS_API_KEY:-}" ]; then
    log "ORS_API_KEY present (${#ORS_API_KEY} chars)."
else
    log "WARNING: ORS_API_KEY is empty — routing features will not work."
fi


log "Update complete."
log "-----------------------------------"

exit 0